### ISSUE TITLE
npm run test报错

### ISSUE THREAD

**Issue by leexiaosi** [swan-team/swan-core#7]
运行
```
npm run test
```
报错如下

```
Chrome 71.0.3578 (Mac OS X 10.14.0) ERROR
  {
    "message": "An error was thrown in afterAll\nReferenceError: App is not defined\n    at <Jasmine>\n    at Suite.<anonymous> (http://localhost:9877test/spec/app-page.spec.js:9:5)\n    at <Jasmine>\n    at http://localhost:9877test/spec/app-page.spec.js:1:1",
    "str": "An error was thrown in afterAll\nReferenceError: App is not defined\n    at <Jasmine>\n    at Suite.<anonymous> (http://localhost:9877test/spec/app-page.spec.js:9:5)\n    at <Jasmine>\n    at http://localhost:9877test/spec/app-page.spec.js:1:1"
  }

Chrome 71.0.3578 (Mac OS X 10.14.0): Executed 0 of 20 ERROR (0.002 secs / 0 secs)
```
尝试修改 `karma.conf.js` 配置，变更加载顺序
- mock.js
- master.mock.js
- slave.mock.js

但例如`src/utils/swan-events/index.js` 文件中 `swanGlobal` 的地方都会导致引用报错。

**Comment by houyu01** [comment]
收到，这块本周会增加
